import turtle

TURTLESPEED = 0
TURTLESHAPE = "circle"
PENSIZE = 4
screen = turtle.Screen()
screen.bgcolor("black")
screen.tracer(10)
james = turtle.Turtle()
bob = turtle.Turtle()
john = turtle.Turtle()
joe = turtle.Turtle()
johnny = turtle.Turtle()
james.shape(TURTLESHAPE)
bob.shape(TURTLESHAPE)
john.shape(TURTLESHAPE)
joe.shape(TURTLESHAPE)
johnny.shape(TURTLESHAPE)
james.color("DarkGray")
bob.color("LightBlue")
john.color("NavyBlue")
joe.color("white")
johnny.color("LimeGreen")
james.speed(TURTLESPEED)
bob.speed(TURTLESPEED)
john.speed(TURTLESPEED)
joe.speed(TURTLESPEED)
johnny.speed(TURTLESPEED)
james.pensize(PENSIZE)
bob.pensize(PENSIZE)
john.pensize(PENSIZE)
joe.pensize(PENSIZE)
johnny.pensize(PENSIZE)

angle = float(screen.textinput("angle", "what angle do you want? "))

for step_size in range(10, 4000000, 1):
#     james.stamp()
#     bob.stamp()
#     john.stamp()
#     joe.stamp()
#     johnny.stamp()
    james.forward(step_size)
    bob.forward(step_size + 1)
    john.forward(step_size + 2)
    joe.forward(step_size + 3)
    johnny.forward(step_size + 4)
    james.left(angle + (angle / 50))
    bob.left(angle + (angle / 40))
    john.left(angle + (angle / 30))
    joe.left(angle + (angle / 20))
    johnny.left(angle + (angle / 10))
